In [1]:
import pandas as pd
from pathlib import Path

In [3]:
# store the file paths into variables
vehicle_master_data = Path("vehicles.csv")
vehicle_price_data = Path('prices_clean.csv')

In [7]:
# read in the files
vehicle_master_data_df = pd.read_csv(vehicle_master_data)
vehicle_price_data_df = pd.read_csv(vehicle_price_data)

/var/folders/5r/qv0zmnq95tb4t8f_16fhk2m80000gp/T/ipykernel_36395/1188489123.py:2: DtypeWarning: Columns (72,74,75,77) have mixed types. Specify dtype option on import or set low_memory=False.
  vehicle_master_data_df = pd.read_csv(vehicle_master_data)

In [18]:
# remove the unnecessary columns then filter to 2023

vehicle_2023_master_df = vehicle_master_data_df[['year','make','model','comb08', 'cylinders', 'drive', 'fuelType', 'VClass', 'baseModel' ]]

vehicle_2023_master_df = vehicle_2023_master_df[vehicle_2023_master_df['year'] == 2023]
vehicle_2023_master_df

,year,make,model,comb08,cylinders,drive,fuelType,VClass,baseModel
38566,2023,Land Rover,Defender 90,19,4.0,4-Wheel Drive,Premium,Standard Sport Utility Vehicle 4WD,Defender
38570,2023,Kia,Sportage FWD,28,4.0,Front-Wheel Drive,Regular,Small Sport Utility Vehicle 2WD,Sportage
38571,2023,Kia,Sportage AWD,25,4.0,All-Wheel Drive,Regular,Small Sport Utility Vehicle 4WD,Sportage
38572,2023,Land Rover,Discovery,21,4.0,4-Wheel Drive,Premium,Standard Sport Utility Vehicle 4WD,Discovery
38573,2023,Land Rover,Discovery MHEV,22,6.0,4-Wheel Drive,Premium,Standard Sport Utility Vehicle 4WD,Discovery
...,...,...,...,...,...,...,...,...,...
40925,2023,Toyota,Prius Prime,48,4.0,Front-Wheel Drive,Regular Gas and Electricity,Midsize Cars,Prius Prime
40926,2023,Toyota,Prius Prime SE,52,4.0,Front-Wheel Drive,Regular Gas and Electricity,Midsize Cars,Prius Prime
40928,2023,Toyota,RAV4 Prime 4WD,38,4.0,All-Wheel Drive,Regular Gas and Electricity,Small Sport Utility Vehicle 4WD,RAV4 Prime
40981,2023,Mercedes-Benz,S580e 4matic,23,6.0,All-Wheel Drive,Premium and Electricity,Large Cars,S-Class
40983,2023,Mitsubishi,Outlander PHEV,26,4.0,All-Wheel Drive,Regular Gas and Electricity,Standard Sport Utility Vehicle 4WD,Outlander

In [28]:
# attempt to combine the two DFs
combined_vehicle_data = pd.merge(vehicle_price_data_df, vehicle_2023_master_df, on=['make', 'model'], how='left')
combined_vehicle_data = combined_vehicle_data[['year_x', 'make', 'model', 'price', 'VClass']]
combined_vehicle_data

      year_x   make                       model     price VClass
0       2023  Honda                     Elevate   14530.0    NaN
1       2023  Honda                           e   37140.0    NaN
2       2023  Honda                   e Advance   37140.0    NaN
3       2023  Honda             Pilot Elite AWD   52030.0    NaN
4       2023  Honda  Pilot EX-L 8-Passenger AWD   42310.0    NaN
...      ...    ...                         ...       ...    ...
1190    2023  Tesla               S Performance  104990.0    NaN
1191    2023  Tesla               X Performance  120990.0    NaN
1192    2023  Tesla          Model 3 Long Range   51990.0    NaN
1193    2023  Tesla               Model X Plaid  119990.0    NaN
1194    2023  Tesla          Model X Long Range  107990.0    NaN

[1195 rows x 5 columns]

In [29]:
combined_vehicle_data.to_csv('combined_vehicle_data.csv', index=False)